//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace SQLiteSyncCOMCsharp.SQLiteSyncCOM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SyncSoap", Namespace="http://sqlite-sync.com/")]
    public partial class Sync : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReceiveDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataForSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncCompletedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullDBSchemaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sync() {
            this.Url = global::SQLiteSyncCOMCsharp.Properties.Settings.Default.SQLiteSyncCOMCsharp_SQLiteSyncCOM_Sync;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReceiveDataCompletedEventHandler ReceiveDataCompleted;
        
        /// <remarks/>
        public event GetDataForSyncCompletedEventHandler GetDataForSyncCompleted;
        
        /// <remarks/>
        public event SyncCompletedCompletedEventHandler SyncCompletedCompleted;
        
        /// <remarks/>
        public event GetFullDBSchemaCompletedEventHandler GetFullDBSchemaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sqlite-sync.com/ReceiveData", RequestNamespace="http://sqlite-sync.com/", ResponseNamespace="http://sqlite-sync.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReceiveData(string subscriber, string data) {
            this.Invoke("ReceiveData", new object[] {
                        subscriber,
                        data});
        }
        
        /// <remarks/>
        public void ReceiveDataAsync(string subscriber, string data) {
            this.ReceiveDataAsync(subscriber, data, null);
        }
        
        /// <remarks/>
        public void ReceiveDataAsync(string subscriber, string data, object userState) {
            if ((this.ReceiveDataOperationCompleted == null)) {
                this.ReceiveDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveDataOperationCompleted);
            }
            this.InvokeAsync("ReceiveData", new object[] {
                        subscriber,
                        data}, this.ReceiveDataOperationCompleted, userState);
        }
        
        private void OnReceiveDataOperationCompleted(object arg) {
            if ((this.ReceiveDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sqlite-sync.com/GetDataForSync", RequestNamespace="http://sqlite-sync.com/", ResponseNamespace="http://sqlite-sync.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDataForSync(string subscriber, string table) {
            object[] results = this.Invoke("GetDataForSync", new object[] {
                        subscriber,
                        table});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataForSyncAsync(string subscriber, string table) {
            this.GetDataForSyncAsync(subscriber, table, null);
        }
        
        /// <remarks/>
        public void GetDataForSyncAsync(string subscriber, string table, object userState) {
            if ((this.GetDataForSyncOperationCompleted == null)) {
                this.GetDataForSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataForSyncOperationCompleted);
            }
            this.InvokeAsync("GetDataForSync", new object[] {
                        subscriber,
                        table}, this.GetDataForSyncOperationCompleted, userState);
        }
        
        private void OnGetDataForSyncOperationCompleted(object arg) {
            if ((this.GetDataForSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataForSyncCompleted(this, new GetDataForSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sqlite-sync.com/SyncCompleted", RequestNamespace="http://sqlite-sync.com/", ResponseNamespace="http://sqlite-sync.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncCompleted(string syncId) {
            this.Invoke("SyncCompleted", new object[] {
                        syncId});
        }
        
        /// <remarks/>
        public void SyncCompletedAsync(string syncId) {
            this.SyncCompletedAsync(syncId, null);
        }
        
        /// <remarks/>
        public void SyncCompletedAsync(string syncId, object userState) {
            if ((this.SyncCompletedOperationCompleted == null)) {
                this.SyncCompletedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncCompletedOperationCompleted);
            }
            this.InvokeAsync("SyncCompleted", new object[] {
                        syncId}, this.SyncCompletedOperationCompleted, userState);
        }
        
        private void OnSyncCompletedOperationCompleted(object arg) {
            if ((this.SyncCompletedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncCompletedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sqlite-sync.com/GetFullDBSchema", RequestNamespace="http://sqlite-sync.com/", ResponseNamespace="http://sqlite-sync.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFullDBSchema(string subscriber) {
            object[] results = this.Invoke("GetFullDBSchema", new object[] {
                        subscriber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFullDBSchemaAsync(string subscriber) {
            this.GetFullDBSchemaAsync(subscriber, null);
        }
        
        /// <remarks/>
        public void GetFullDBSchemaAsync(string subscriber, object userState) {
            if ((this.GetFullDBSchemaOperationCompleted == null)) {
                this.GetFullDBSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullDBSchemaOperationCompleted);
            }
            this.InvokeAsync("GetFullDBSchema", new object[] {
                        subscriber}, this.GetFullDBSchemaOperationCompleted, userState);
        }
        
        private void OnGetFullDBSchemaOperationCompleted(object arg) {
            if ((this.GetFullDBSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullDBSchemaCompleted(this, new GetFullDBSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ReceiveDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetDataForSyncCompletedEventHandler(object sender, GetDataForSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataForSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataForSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SyncCompletedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetFullDBSchemaCompletedEventHandler(object sender, GetFullDBSchemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullDBSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullDBSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591