// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SQLiteSyncCOMLibXamarin.Droid.demo_sqlite_sync_com {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SyncSoap", Namespace="http://sqlite-sync.com/")]
    public partial class Sync : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReceiveDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataForSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncCompletedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullDBSchemaOperationCompleted;
        
        /// CodeRemarks
        public Sync() {
            this.Url = "http://demo.sqlite-sync.com/sync.asmx";
        }
        
        public Sync(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event ReceiveDataCompletedEventHandler ReceiveDataCompleted;
        
        /// CodeRemarks
        public event GetDataForSyncCompletedEventHandler GetDataForSyncCompleted;
        
        /// CodeRemarks
        public event SyncCompletedCompletedEventHandler SyncCompletedCompleted;
        
        /// CodeRemarks
        public event GetFullDBSchemaCompletedEventHandler GetFullDBSchemaCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sqlite-sync.com/ReceiveData", RequestNamespace="http://sqlite-sync.com/", ResponseNamespace="http://sqlite-sync.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReceiveData(string subscriber, string data) {
            this.Invoke("ReceiveData", new object[] {
                        subscriber,
                        data});
        }
        
        /// CodeRemarks
        public void ReceiveDataAsync(string subscriber, string data) {
            this.ReceiveDataAsync(subscriber, data, null);
        }
        
        /// CodeRemarks
        public void ReceiveDataAsync(string subscriber, string data, object userState) {
            if ((this.ReceiveDataOperationCompleted == null)) {
                this.ReceiveDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveDataOperationCompleted);
            }
            this.InvokeAsync("ReceiveData", new object[] {
                        subscriber,
                        data}, this.ReceiveDataOperationCompleted, userState);
        }
        
        private void OnReceiveDataOperationCompleted(object arg) {
            if ((this.ReceiveDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sqlite-sync.com/GetDataForSync", RequestNamespace="http://sqlite-sync.com/", ResponseNamespace="http://sqlite-sync.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDataForSync(string subscriber, string table) {
            object[] results = this.Invoke("GetDataForSync", new object[] {
                        subscriber,
                        table});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void GetDataForSyncAsync(string subscriber, string table) {
            this.GetDataForSyncAsync(subscriber, table, null);
        }
        
        /// CodeRemarks
        public void GetDataForSyncAsync(string subscriber, string table, object userState) {
            if ((this.GetDataForSyncOperationCompleted == null)) {
                this.GetDataForSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataForSyncOperationCompleted);
            }
            this.InvokeAsync("GetDataForSync", new object[] {
                        subscriber,
                        table}, this.GetDataForSyncOperationCompleted, userState);
        }
        
        private void OnGetDataForSyncOperationCompleted(object arg) {
            if ((this.GetDataForSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataForSyncCompleted(this, new GetDataForSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sqlite-sync.com/SyncCompleted", RequestNamespace="http://sqlite-sync.com/", ResponseNamespace="http://sqlite-sync.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncCompleted(string syncId) {
            this.Invoke("SyncCompleted", new object[] {
                        syncId});
        }
        
        /// CodeRemarks
        public void SyncCompletedAsync(string syncId) {
            this.SyncCompletedAsync(syncId, null);
        }
        
        /// CodeRemarks
        public void SyncCompletedAsync(string syncId, object userState) {
            if ((this.SyncCompletedOperationCompleted == null)) {
                this.SyncCompletedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncCompletedOperationCompleted);
            }
            this.InvokeAsync("SyncCompleted", new object[] {
                        syncId}, this.SyncCompletedOperationCompleted, userState);
        }
        
        private void OnSyncCompletedOperationCompleted(object arg) {
            if ((this.SyncCompletedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncCompletedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sqlite-sync.com/GetFullDBSchema", RequestNamespace="http://sqlite-sync.com/", ResponseNamespace="http://sqlite-sync.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFullDBSchema(string subscriber) {
            object[] results = this.Invoke("GetFullDBSchema", new object[] {
                        subscriber});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void GetFullDBSchemaAsync(string subscriber) {
            this.GetFullDBSchemaAsync(subscriber, null);
        }
        
        /// CodeRemarks
        public void GetFullDBSchemaAsync(string subscriber, object userState) {
            if ((this.GetFullDBSchemaOperationCompleted == null)) {
                this.GetFullDBSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullDBSchemaOperationCompleted);
            }
            this.InvokeAsync("GetFullDBSchema", new object[] {
                        subscriber}, this.GetFullDBSchemaOperationCompleted, userState);
        }
        
        private void OnGetFullDBSchemaOperationCompleted(object arg) {
            if ((this.GetFullDBSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullDBSchemaCompleted(this, new GetFullDBSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void ReceiveDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GetDataForSyncCompletedEventHandler(object sender, GetDataForSyncCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataForSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataForSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void SyncCompletedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GetFullDBSchemaCompletedEventHandler(object sender, GetFullDBSchemaCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullDBSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullDBSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
